import { Inter } from 'next/font/google'
import './globals.css'
import { Footer } from './components/Footer'
import { Navbar } from './components/Navbar'
import Providers from './util/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:text-white text-black bg-gray-100`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
